color: null
fieldLayouts:
  3cf5dc8d-0729-497b-9de6-0352c09ab196:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b96a97fe-5da5-4cb2-81b1-6413d90fee6a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9022336e-4ca6-440f-9c19-3f878aa04396 # image slider
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ec86412-d769-4cc9-a660-b0e7ba61854e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7cec1d6b-4c59-4e82-ab8a-7fdb24c20465 # rich text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2939b93f-bda1-4779-9cee-8089498ab5b7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cd06fc77-8527-46df-b19d-47534adb8b27 # full text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6d8b319-b3bc-4e3c-88d5-f603fb6384bd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1417cccc-ab33-480d-b15d-401ab55c9029 # intro text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1195e010-0e33-4e3b-8d0b-7f026ca7e05e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e6ce7b17-62d1-4aea-b767-08158884acda
        userCondition: null
handle: accesoires
hasTitleField: true
icon: ''
name: accesoires
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
