color: null
fieldLayouts:
  04cdaa2a-bcc5-4333-b5a4-d690f7d62c5f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d99a103b-0af6-40c4-917a-a0a36325ce3b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7cec1d6b-4c59-4e82-ab8a-7fdb24c20465 # rich text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ea796ba-5393-4dbd-b91b-3e3d6c118b6e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a07fd20c-3e0e-453d-b8ba-4b88f449696b # about us
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c1122da-e915-42a6-9a22-090f3adc6f88
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f1e3d31f-5f80-4242-a1de-705fe869d7a8 # email
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d386ad1-b230-41ea-85f8-fefa8ed3416f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5c0a68b4-516d-4e33-a060-bd654f3e0213 # phone number
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34bee877-c12d-48a1-a4d1-ba47e838d005
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cd06fc77-8527-46df-b19d-47534adb8b27 # full text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9bda23e1-e5c3-42a3-bdaa-aa5bf2e8973a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1417cccc-ab33-480d-b15d-401ab55c9029 # intro text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: daec4e1e-c0b5-451a-9a56-9b3333cb2f1f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5991ae8b-5a27-493e-97c1-dcee0fb3fb6d
        userCondition: null
handle: contactPagina
hasTitleField: true
icon: address-book
name: 'contact pagina'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
