color: null
fieldLayouts:
  e27b7e8d-8b29-4978-9429-942ee429e12e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8cc394f9-213a-47c3-8e28-6d44beea0932
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f46a6409-633b-47fd-9eb5-c694e0d4c140 # banner image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8578fb2c-cbec-42fb-9f1a-4fb0c39f5930
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1417cccc-ab33-480d-b15d-401ab55c9029 # intro text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fcfda9da-9d9d-4deb-8072-88f8d963fd71
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cd06fc77-8527-46df-b19d-47534adb8b27 # full text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c19915dd-1983-4b0c-b20a-73de1512b877
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4d265f2c-1932-4d4b-9d0e-f29acf60d6d9
        userCondition: null
handle: homepage
hasTitleField: true
icon: house
name: homepage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
