color: null
fieldLayouts:
  21cfe2bb-0851-4536-aef9-2dcc11a65935:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 12357744-bb4e-4b4e-aa76-b6a24ce9a6ec
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 31dfce39-3d42-40a1-85e2-3230c8259b72
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 855861b2-7086-4650-8411-a4be0f0c1cd6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5fca1b34-afc2-4607-8a41-fcb3ce11547b
        userCondition: null
handle: mainImage
hasTitleField: true
icon: image
name: 'main image'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
