color: null
fieldLayouts:
  92e241c9-f776-4157-8e37-8a136cd558e1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d374f08f-4e93-4d17-94a8-1f3458fff6e3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5bd4c651-f112-4f11-8851-732d9c6c7b58 # banner image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08d25e3d-7de3-4d9a-8ead-5821306c5126
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1417cccc-ab33-480d-b15d-401ab55c9029 # intro text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7c5355d-8d01-485d-9e85-965ebd3e43ea
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cd06fc77-8527-46df-b19d-47534adb8b27 # full text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5a2b98cc-b03b-485f-b504-a1a46f1daa9a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7cec1d6b-4c59-4e82-ab8a-7fdb24c20465 # rich text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d0b9af4b-095d-49ee-9050-88ab0e5b7a71
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cbde35a6-4486-4ff7-a600-733a073e266a #  store categories
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e94f87dc-b2f7-467e-bb08-84c3a140326f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0cecfaf6-800a-4da4-892e-e351ad5c25c5
        userCondition: null
handle: sportFilter
hasTitleField: true
icon: ''
name: 'sport fitler'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
