altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  8774a877-0305-4865-9346-7dbc208af2b5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: bc0a2050-8726-4658-bdc4-c17d4c836205
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7f8953c2-6f99-48ec-9037-06e2949602ff
        userCondition: null
fs: asset
handle: accesoires
name: accesoires
sortOrder: 3
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
