altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  8c14e619-b2fa-42c4-98de-b149d5c78787:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 7ca1377b-038c-41f6-bc31-f9e3849bfe0e
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: ba31c6b0-ffb9-44ac-873f-c64c5a21bbeb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f1641278-5611-46a7-9b4f-22984c16604b
        userCondition: null
fs: assets
handle: homepageAsssets
name: 'homepage asssets'
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: assets
transformSubpath: ''
