columnSuffix: null
handle: aboutUs
instructions: null
name: 'about us'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  purifierConfig: Default.json
  purifyHtml: true
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  showHtmlButtonForNonAdmins: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  tinymceConfig: Default.json
translationKeyFormat: null
translationMethod: none
type: abmat\tinymce\Field
