dateModified: 1721844573
email:
  fromEmail: sedaezzat@icloud.com
  fromName: Sport
  transportType: craft\mail\transportadapters\Sendmail
fs:
  assets:
    hasUrls: true
    name: assets
    settings:
      path: '@webroot/images'
    type: craft\fs\Local
    url: '@web/images'
meta:
  __names__:
    5c0a68b4-516d-4e33-a060-bd654f3e0213: 'phone number' # phone number
    7cec1d6b-4c59-4e82-ab8a-7fdb24c20465: 'rich text' # rich text
    7e9bf105-b884-4c5d-9218-047703c51ec6: 'home detail' # home detail
    24b335d5-9e12-4faf-a1de-02925c8d7606: 'homepage asssets' # homepage asssets
    44cd1cbe-d5ab-4cd5-92c2-da3c31250bf9: footer # footer
    45fffe05-b731-48ec-9532-e07d8d939850: homepage # homepage
    49d23e08-aa8f-459b-af22-ff6498494a3d: Sport # Sport
    671adc41-c795-47a7-a032-75cc596ca3c0: Sport # Sport
    893a89cf-fdf1-45cf-bfaa-8353d01eb5d5: links # links
    1417cccc-ab33-480d-b15d-401ab55c9029: 'intro text' # intro text
    8198bac8-efc9-4a7c-87c2-8cff3f53d6d0: banner # banner
    86017f27-1e19-42a4-8dfe-6a74d3065132: 'Public Schema' # Public Schema
    a3eb63ed-c51d-4923-974c-6a330cc82d64: thumbnail # thumbnail
    b3c4ea91-8c24-4e93-9fab-c86e31f31d96: header # header
    c2cf347b-466e-49d8-a51f-ee2665ded79e: 'about us' # about us
    c6c1c12c-b89e-40d5-bae5-34b679cd7436: footer # footer
    c4277b1f-b97c-4110-8714-81968a65d02d: homepage # homepage
    c491729c-afce-4e5c-9296-85d7fbe40364: 'header title' # header title
    cd06fc77-8527-46df-b19d-47534adb8b27: 'full text' # full text
    d78a8aeb-4963-46e8-86e7-2cf811ffd6a4: 'header title' # header title
    f1e3d31f-5f80-4242-a1de-705fe869d7a8: email # email
    f46a6409-633b-47fd-9eb5-c694e0d4c140: 'banner image' # banner image
plugins:
  abm-tinymce:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: Sport
  schemaVersion: 5.0.0.21
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
