defaultPlacement: end
enableVersioning: true
entryTypes:
  - cf52bf10-5d39-414e-9642-0c6c48aead7d # contact pagina
handle: contactPagina
maxAuthors: 1
name: 'Contact pagina'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  49d23e08-aa8f-459b-af22-ff6498494a3d: # Sport
    enabledByDefault: true
    hasUrls: true
    template: contact.twig
    uriFormat: contact-pagina
type: single
