defaultPlacement: end
enableVersioning: true
entryTypes:
  - 74dc0981-c0f4-40d0-b935-d716a9c31c38 # detail pagina
handle: detailPagina
maxAuthors: 1
name: 'detail pagina'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  49d23e08-aa8f-459b-af22-ff6498494a3d: # Sport
    enabledByDefault: true
    hasUrls: true
    template: categories/entry.twig
    uriFormat: 'detail-pagina/{slug}'
type: channel
