defaultPlacement: end
enableVersioning: true
entryTypes:
  - c491729c-afce-4e5c-9296-85d7fbe40364 # header title
handle: headerTitle
maxAuthors: 1
name: 'header title'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  49d23e08-aa8f-459b-af22-ff6498494a3d: # Sport
    enabledByDefault: true
    hasUrls: true
    template: header-title/_entry
    uriFormat: header-title
type: single
