defaultPlacement: end
enableVersioning: true
entryTypes:
  - 45fffe05-b731-48ec-9532-e07d8d939850 # homepage
handle: homeDetail
maxAuthors: 1
name: 'home detail'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  49d23e08-aa8f-459b-af22-ff6498494a3d: # Sport
    enabledByDefault: true
    hasUrls: true
    template: home-detail/_entry
    uriFormat: 'home-detail/{slug}'
type: channel
