defaultPlacement: end
enableVersioning: true
entryTypes:
  - 3ac28252-8914-458b-9eac-08ef876bb135 # sport fitler
handle: sportFilter
maxAuthors: 1
name: 'sport filter'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  49d23e08-aa8f-459b-af22-ff6498494a3d: # Sport
    enabledByDefault: true
    hasUrls: true
    template: sport.twig
    uriFormat: 'sport/{slug}'
type: channel
