defaultPlacement: end
enableVersioning: true
entryTypes:
  - 759b3c6e-f6ec-4443-a57e-6b1f254a139f # store categories
handle: storeCategories
maxAuthors: 1
name: 'store categories'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  49d23e08-aa8f-459b-af22-ff6498494a3d: # Sport
    enabledByDefault: true
    hasUrls: true
    template: sport.twig
    uriFormat: 'store-categories/{slug}'
structure:
  maxLevels: null
  uid: ab13392f-8d79-44dd-9f67-c4fc4e445558
type: structure
